package com.cn.lab.model;

import java.util.Date;

public class SysMenu {

	//当做dto使用的字段------start
	private String ids;//获取页面上多个id拼接值,逗号分隔
	
	//当做dto使用的字段------end
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.id
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private Integer id;
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.menucode
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private String menucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.menuname
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.menulevel
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private Integer menulevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.menuurl
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private String menuurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.menupic
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private String menupic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.ctime
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.cuser
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private Integer cuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.utime
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.uuser
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    private Integer uuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.id
     *
     * @return the value of sysmenu.id
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.id
     *
     * @param id the value for sysmenu.id
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.menucode
     *
     * @return the value of sysmenu.menucode
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.menucode
     *
     * @param menucode the value for sysmenu.menucode
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.menuname
     *
     * @return the value of sysmenu.menuname
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.menuname
     *
     * @param menuname the value for sysmenu.menuname
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.menulevel
     *
     * @return the value of sysmenu.menulevel
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public Integer getMenulevel() {
        return menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.menulevel
     *
     * @param menulevel the value for sysmenu.menulevel
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setMenulevel(Integer menulevel) {
        this.menulevel = menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.menuurl
     *
     * @return the value of sysmenu.menuurl
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.menuurl
     *
     * @param menuurl the value for sysmenu.menuurl
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl == null ? null : menuurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.menupic
     *
     * @return the value of sysmenu.menupic
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public String getMenupic() {
        return menupic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.menupic
     *
     * @param menupic the value for sysmenu.menupic
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setMenupic(String menupic) {
        this.menupic = menupic == null ? null : menupic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.ctime
     *
     * @return the value of sysmenu.ctime
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.ctime
     *
     * @param ctime the value for sysmenu.ctime
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.cuser
     *
     * @return the value of sysmenu.cuser
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public Integer getCuser() {
        return cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.cuser
     *
     * @param cuser the value for sysmenu.cuser
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setCuser(Integer cuser) {
        this.cuser = cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.utime
     *
     * @return the value of sysmenu.utime
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.utime
     *
     * @param utime the value for sysmenu.utime
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.uuser
     *
     * @return the value of sysmenu.uuser
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public Integer getUuser() {
        return uuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.uuser
     *
     * @param uuser the value for sysmenu.uuser
     *
     * @mbggenerated Mon Dec 25 23:37:17 CST 2017
     */
    public void setUuser(Integer uuser) {
        this.uuser = uuser;
    }

	public String getIds() {
		return ids;
	}

	public void setIds(String ids) {
		this.ids = ids;
	}

	public Integer getPid() {
		
		return pid==null?0:pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Override
	public String toString() {
		return "SysMenu [ids=" + ids + ", id=" + id + ", pid=" + pid + ", menucode=" + menucode + ", menuname=" + menuname + ", menulevel=" + menulevel + ", menuurl=" + menuurl + ", menupic="
				+ menupic + ", ctime=" + ctime + ", cuser=" + cuser + ", utime=" + utime + ", uuser=" + uuser + "]";
	}
}