package com.cn.lab.model;

public class SysRoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrolemenu.id
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrolemenu.roleid
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrolemenu.menuid
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    private Integer menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrolemenu.id
     *
     * @return the value of sysrolemenu.id
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrolemenu.id
     *
     * @param id the value for sysrolemenu.id
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrolemenu.roleid
     *
     * @return the value of sysrolemenu.roleid
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrolemenu.roleid
     *
     * @param roleid the value for sysrolemenu.roleid
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrolemenu.menuid
     *
     * @return the value of sysrolemenu.menuid
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrolemenu.menuid
     *
     * @param menuid the value for sysrolemenu.menuid
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }
}