package com.cn.lab.model;

import java.util.Date;

public class SysRole {

	//当做dto使用的字段------start
	private String ids;//获取页面上多个id拼接值,逗号分隔
	
	//当做dto使用的字段------end
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.id
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.rolecode
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.rolename
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.ctime
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.cuser
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    private Integer cuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.utime
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.uuser
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    private Integer uuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.id
     *
     * @return the value of sysrole.id
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.id
     *
     * @param id the value for sysrole.id
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.rolecode
     *
     * @return the value of sysrole.rolecode
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.rolecode
     *
     * @param rolecode the value for sysrole.rolecode
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.rolename
     *
     * @return the value of sysrole.rolename
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.rolename
     *
     * @param rolename the value for sysrole.rolename
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.ctime
     *
     * @return the value of sysrole.ctime
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.ctime
     *
     * @param ctime the value for sysrole.ctime
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.cuser
     *
     * @return the value of sysrole.cuser
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public Integer getCuser() {
        return cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.cuser
     *
     * @param cuser the value for sysrole.cuser
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public void setCuser(Integer cuser) {
        this.cuser = cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.utime
     *
     * @return the value of sysrole.utime
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.utime
     *
     * @param utime the value for sysrole.utime
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.uuser
     *
     * @return the value of sysrole.uuser
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public Integer getUuser() {
        return uuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.uuser
     *
     * @param uuser the value for sysrole.uuser
     *
     * @mbggenerated Mon Dec 25 23:37:39 CST 2017
     */
    public void setUuser(Integer uuser) {
        this.uuser = uuser;
    }

	public String getIds() {
		return ids;
	}

	public void setIds(String ids) {
		this.ids = ids;
	}
}