package com.cn.lab.model;

import java.util.Date;

import org.apache.commons.lang.StringUtils;

public class SysUser {
	
	//当做dto使用的字段------start
	private String ids;//获取页面上多个id拼接值,逗号分隔
	
	//当做dto使用的字段------end
	
	
	
    public String getIds() {
		return ids;
	}

	public void setIds(String ids) {
		this.ids = ids;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.id
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.usercode
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private String usercode;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.username
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.passwrod
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private String passwrod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.sex
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.phone
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.ctime
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private Date ctime = new Date();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.cuser
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private Integer cuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.utime
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private Date utime  = new Date();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.uuser
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    private Integer uuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.id
     *
     * @return the value of sysuser.id
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.id
     *
     * @param id the value for sysuser.id
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.usercode
     *
     * @return the value of sysuser.usercode
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public String getUsercode() {
        return StringUtils.trimToNull(usercode);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.usercode
     *
     * @param usercode the value for sysuser.usercode
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.username
     *
     * @return the value of sysuser.username
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public String getUsername() {
        return StringUtils.trimToNull(username);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.username
     *
     * @param username the value for sysuser.username
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.passwrod
     *
     * @return the value of sysuser.passwrod
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public String getPasswrod() {
        return passwrod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.passwrod
     *
     * @param passwrod the value for sysuser.passwrod
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setPasswrod(String passwrod) {
        this.passwrod = passwrod == null ? null : passwrod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.sex
     *
     * @return the value of sysuser.sex
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public String getSex() {
        return StringUtils.trimToNull(sex);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.sex
     *
     * @param sex the value for sysuser.sex
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.phone
     *
     * @return the value of sysuser.phone
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public String getPhone() {
        return StringUtils.trimToNull(phone);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.phone
     *
     * @param phone the value for sysuser.phone
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.ctime
     *
     * @return the value of sysuser.ctime
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.ctime
     *
     * @param ctime the value for sysuser.ctime
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.cuser
     *
     * @return the value of sysuser.cuser
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public Integer getCuser() {
        return cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.cuser
     *
     * @param cuser the value for sysuser.cuser
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setCuser(Integer cuser) {
        this.cuser = cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.utime
     *
     * @return the value of sysuser.utime
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.utime
     *
     * @param utime the value for sysuser.utime
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.uuser
     *
     * @return the value of sysuser.uuser
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public Integer getUuser() {
        return uuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.uuser
     *
     * @param uuser the value for sysuser.uuser
     *
     * @mbggenerated Mon Dec 25 23:38:23 CST 2017
     */
    public void setUuser(Integer uuser) {
        this.uuser = uuser;
    }

    @Override
	public String toString() {
		return "SysUser [id=" + id + ", usercode=" + usercode + ", username=" + username + ", passwrod=" + passwrod + ", sex=" + sex + ", phone=" + phone + ", ctime=" + ctime + ", cuser=" + cuser
				+ ", utime=" + utime + ", uuser=" + uuser + "]";
	}

}