package com.cn.lab.model;

public class SysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserrole.id
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserrole.userid
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserrole.roleid
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserrole.id
     *
     * @return the value of sysuserrole.id
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserrole.id
     *
     * @param id the value for sysuserrole.id
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserrole.userid
     *
     * @return the value of sysuserrole.userid
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserrole.userid
     *
     * @param userid the value for sysuserrole.userid
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserrole.roleid
     *
     * @return the value of sysuserrole.roleid
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserrole.roleid
     *
     * @param roleid the value for sysuserrole.roleid
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}