package com.cn.lab.dao;

import com.cn.lab.model.SysRoleMenu;

public interface SysRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrolemenu
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrolemenu
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    int insert(SysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrolemenu
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    int insertSelective(SysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrolemenu
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    SysRoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrolemenu
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    int updateByPrimaryKeySelective(SysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrolemenu
     *
     * @mbggenerated Mon Dec 25 23:37:56 CST 2017
     */
    int updateByPrimaryKey(SysRoleMenu record);
}