package com.cn.lab.dao;

import com.cn.lab.model.SysUserRole;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuserrole
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuserrole
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuserrole
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    int insertSelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuserrole
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    SysUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuserrole
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    int updateByPrimaryKeySelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuserrole
     *
     * @mbggenerated Mon Dec 25 23:38:40 CST 2017
     */
    int updateByPrimaryKey(SysUserRole record);
}